3. Development/PetVet/PetVet/urls.py
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from products import views as products_views
from .views import *

urlpatterns = [
	path('login/', login_page, name='login_page'),
	path('logout/', logout_page, name='logout_page'),
	path('registration/', register_page, name='register_page'),
	path('registration-complete/', register_complete_page, name='register_complete_page'),
	path('admin/', admin.site.urls, name='admin'),

	url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
	# Includes
    path('cart', include('cart.urls')),
    path('', include('orders.urls')),
    path('', include('products.urls')), # ESTE TIENE Q IR ULTIMO!!
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

3. Development/PetVet/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

3. Development/PetVet/products/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from .views import product_list, product_detail

app_name = 'products'


urlpatterns = [
    path('', product_list, name="products_list"),
    url(r'^(?P<slug>[-\w]+)/$', product_list, name="product_list_by_category"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name="product_detail"),
]

3. Development/PetVet/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% include 'base/head/_head.html' %}
	
	<title>{% block title %}{% endblock %}</title>
</head>
<body class="animsition">
	<div class="content">
	{% include 'base/navbar.html' %}
	{% block content %}
    {% endblock %}
	</div>
	{% include 'base/footer/_footer.html' %}
	{% block customjs %}
    {% endblock %}
</body>
</html>

3. Development/PetVet/templates/base/navbar.html
{% load static %}
<!-- Header -->
<header class="header1">
	<!-- Header desktop -->
	<div class="container-menu-header">
		<div class="wrap_header">
			<div class="header-aligner">
				<!-- Logo -->
				<div class="header-logo">
					<a id="logo-wrapper" href="/" class="logo-mobile">
						<img id="logo" src="{% static "images/icons/logo.png" alt="%}" IMG-LOGO">
						<img id="logo-hover" src="{% static "images/icons/logo-hover.png" alt="%}" IMG-LOGO">
					</a>
				</div>
				<!-- Menu -->
				<span class="header-divide"></span>
				<div class="wrap-menu">
					<div class="menu">
						<form action="{% url "products:products_list" %}" method="get">
							<div id="search-container" class="bo4">
								<input name="search" type="search" id="search" class="s-text7 size1 p-l-23 p-r-50" placeholder="I'm looking for...">
							</div>
							<button type="submit" id="search-icon" class="fa fa-search" />
						</form>
					</div>
				</div>
				<span class="header-divide"></span>

				<!-- Header Icon -->
				<div class="wrap-icons">
					<div class="header-icons">
						{% if not request.user.is_anonymous %}
			            <p>{{ user }}</p>
						<span class="divide1"></span>
						<img src="{% static "images/icons/icon-header-01.png" class="header-%}" icon1" alt="ICON">
						<span class="linedivide1"></span>
						{% endif %}

						<a id="icon-header-01-wrapper" href="/orders" class="header-wrapicon1 dis-block" data-toggle="tooltip" title="My Orders">
							<img id="icon-header-01" src="{% static "images/icons/icon-header-03.png" class="header-%}" icon1" alt="ICON">
							<img id="icon-header-01-hover" src="{% static "images/icons/icon-header-03-hover.png" class="header-%}" icon1" alt="ICON">
						</a>

						<span class="linedivide1"></span>

						<a id="icon-header-02-wrapper" href="/cart" class="header-wrapicon1 dis-block header-2" data-toggle="tooltip" title="My Cart">
							<img id="icon-header-02" src="{% static "images/icons/icon-header-02.png" class="header-%}" icon1" alt="ICON">
							<img id="icon-header-02-hover" src="{% static "images/icons/icon-header-02-hover.png" class="header-%}" icon1" alt="ICON">
							<span class="header-icons-noti">0</span>
						</a>

						<span class="linedivide1"></span>

						{% if request.user.is_anonymous %}
						<a id="icon-header-03-wrapper" href="/login" class="header-wrapicon1 dis-block" data-toggle="tooltip" title="Login">
							<img id="icon-header-03" src="{% static "images/icons/door.png" class="header-%}" icon1" alt="ICON">
							<img id="icon-header-03-hover" src="{% static "images/icons/door-hover.png" class="header-%}" icon1" alt="ICON">
						</a>
						{% else %}
						<a id="icon-header-04-wrapper" href="/logout" class="header-wrapicon1 dis-block" data-toggle="tooltip" title="Logout">
							<img id="icon-header-04" src="{% static "images/icons/door-back.png" class="header-%}" icon1" alt="ICON">
							<img id="icon-header-04-hover" src="{% static "images/icons/door-back-hover.png" class="header-%}" icon1" alt="ICON">
						</a>
						{% endif %}
					</div>
				</div>
			</div>	
		</div>
	</div>
	<div class="wrap_header_mobile">
		<!-- Logo moblie -->
		<a id="logo-wrapper" href="/" class="logo-mobile">
			<img id="logo" src="{% static "images/icons/logo.png" alt="%}" IMG-LOGO">
			<img id="logo-hover" src="{% static "images/icons/logo-hover.png" alt="%}" IMG-LOGO">
		</a>

		<!-- Button show menu -->
		<div class="btn-show-menu">
			<!-- Header Icon mobile -->
			<div class="header-icons-mobile">
	            {% if not request.user.is_anonymous %}
	            <p>{{ user }}</p>
				<span class="divide1"></span>
				<img src="{% static "images/icons/icon-header-01.png" class="header-%}" icon1" alt="ICON">
				<span class="linedivide1"></span>
				{% endif %}

				<a id="icon-header-01-wrapper" href="/orders" class="header-wrapicon1 dis-block" data-toggle="tooltip" title="My Orders">
					<img id="icon-header-01" src="{% static "images/icons/icon-header-03.png" class="header-%}" icon1" alt="ICON">
					<img id="icon-header-01-hover" src="{% static "images/icons/icon-header-03-hover.png" class="header-%}" icon1" alt="ICON">
				</a>

				<span class="linedivide1"></span>

				<a id="icon-header-02-wrapper" href="/cart" class="header-wrapicon1 dis-block header-2" data-toggle="tooltip" title="My Cart">
					<img id="icon-header-02" src="{% static "images/icons/icon-header-02.png" class="header-%}" icon1" alt="ICON">
					<img id="icon-header-02-hover" src="{% static "images/icons/icon-header-02-hover.png" class="header-%}" icon1" alt="ICON">
					<span class="header-icons-noti">0</span>
				</a>

				<span class="linedivide1"></span>

				{% if request.user.is_anonymous %}
				<a id="icon-header-03-wrapper" href="/login" class="header-wrapicon1 dis-block" data-toggle="tooltip" title="Login">
					<img id="icon-header-03" src="{% static "images/icons/door.png" class="header-%}" icon1" alt="ICON">
					<img id="icon-header-03-hover" src="{% static "images/icons/door-hover.png" class="header-%}" icon1" alt="ICON">
				</a>
				{% else %}
				<a id="icon-header-04-wrapper" href="/logout" class="header-wrapicon1 dis-block" data-toggle="tooltip" title="Logout">
					<img id="icon-header-04" src="{% static "images/icons/door-back.png" class="header-%}" icon1" alt="ICON">
					<img id="icon-header-04-hover" src="{% static "images/icons/door-back-hover.png" class="header-%}" icon1" alt="ICON">
				</a>
				{% endif %}
			</div>
		</div>
		<div class="container flex-r p-t-8 p-b-8">
			<div class="wrap-menu">
				<div class="menu">
					<form action="#">
						<div id="search-container" class="bo4">
							<input type="search" id="search" class="s-text7 size1 p-l-23 p-r-50" placeholder="I'm looking for...">
						</div>
						<button href="#" id="search-icon" class="fa fa-search"></a>
					</form>
				</div>
			</div>
		</div>
	</div>
</header>