3. Development/PetVet/PetVet/urls.py
from django.views.static import serve
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from products import views as products_views
from .views import *

urlpatterns = [
	path('login/', login_page, name='login_page'),
	path('logout/', logout_page, name='logout_page'),
	path('registration/', register_page, name='register_page'),
	path('registration-complete/', register_complete_page, name='register_complete_page'),
	path('admin/', admin.site.urls, name='admin'),

	url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
	# Includes
    path('cart', include('cart.urls')),
    path('', include('orders.urls')),
    path('', include('products.urls')), # ESTE TIENE Q IR ULTIMO!!
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

3. Development/PetVet/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

3. Development/PetVet/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('orders', views.orders_list, name = 'orders_list'),
    path('order/create/', views.order_create, name = 'order_create')
]

3. Development/PetVet/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

3. Development/PetVet/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from orders.forms import OrderCreateForm 
from django.urls import reverse

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect(reverse('cart:cart_detail'))


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect(reverse('cart:cart_detail'))


def cart_detail(request):
    cart = Cart(request)
    form = OrderCreateForm(request.POST or None)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'form': form, 'cart': cart})

3. Development/PetVet/templates/cart/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    Checkout - PetVet
{% endblock %}


{% block content %}
<!-- Content page -->
    <section class="cart p-b-100">
        <div class="container">
            <!-- Cart item -->

            {% if form.non_field_errors %}
            <div class="non-field-errors">
              {% for err in form.non_field_errors %}
                <p class="alert alert-danger">{{ err }}</p>
              {% endfor %}
            </div>
          {% endif %}

            <div class="container-table-cart pos-relative">
                <div class="wrap-table-shopping-cart">
                    <table class="table-shopping-cart">
                        <tr class="table-head">
                            <th class="p-t-25 p-b-25 p-l-35 p-r-60 p-lr-15-sm"></th>
                            <th class="column-2">Product</th>
                            <th class="column-4 r p-t-25 p-b-25 p-l-35 p-r-60 p-lr-15-sm">Total</th>
                        </tr>
                        {% for item in cart %}
                            {% with product=item.product  %}
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                <tr class="table-row bg-white">
                                    <td class="column-1 p-t-25 p-b-25 p-l-35 p-r-60 p-lr-15-sm">
                                        <div class="cart-img-product b-rad-4 o-f-hidden">
                                            <img src="{{product.image.url}}" alt="IMG-PRODUCT">
                                        </div>
                                    </td>
                                    <td class="column-2">
                                        <div class="m-text23">
                                            {{product.name}}
                                        </div>
                                        <div class="s-text13">
                                            ${{item.price}}
                                        </div>
                                        <div class="p-t-15 block">
                                            <div class="flex-w bo5 of-hidden">
                                                <button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
                                                    <i class="fs-12 fa fa-minus" aria-hidden="true"></i>
                                                </button>

                                                <input class="size8 m-text18 t-center num-product" type="number" id="id_quantity" name="quantity" value="{{item.quantity}}">

                                                <button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
                                                    <i class="fs-12 fa fa-plus" aria-hidden="true"></i>
                                                </button>
                                            </div>
                                            <div class="p-t-8">
                                            <!-- Button -->
                                                {% csrf_token %}
                                                <input type="hidden" name="update" value="True" id="id_update">
                                                <input type="submit" value="Update" class="flex-c-m size4 bg7 bo-rad-15 hov1 s-text14 trans-0-4">
                                                <a href="{% url "cart:cart_remove" product.id %}">
                                                    <div class="flex-c-m size4 bg7 bo-rad-15 hov1 s-text14 trans-0-4 m-t-8">
                                                        Remove
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="column-4 r p-t-25 p-b-25 p-l-35 p-r-60 p-lr-15-sm">${{item.total_price}}</td>
                                </tr>
                            </form>
                            {% endwith %}
                        {% endfor %}
                    </table>
                </div>
            </div>

            <div class="bg-white p-t-25 p-b-25 bo9 p-l-35 p-r-60 p-lr-15-sm">
                <h5 class="m-text20 p-b-24">
                    Cart Totals
                </h5>

                <!--  -->
                <div class="flex-w flex-sb-m p-b-12">
                    <span class="s-text18 w-size19 w-full-sm">
                        Subtotal:
                    </span>

                    <span class="m-text21 w-size20 w-full-sm r-text">
                        ${{ cart.get_total_price }}
                    </span>
                </div>

                <!--  -->
                <form action="{% url "orders:order_create" %}" method="post">
                    {% csrf_token %}
                    <div class="flex-w flex-r bo10 p-t-15 p-b-20">
                        <div class="w-size20 w-full-sm r">
                            <div class="rs2-select2 rs3-select2 rs4-select2 bo4 of-hidden m-t-8 m-b-12">
                                {{form.address}}
                                {{form.address.errors}}
                            </div>

                            <!--<div class="size14 trans-0-4 m-b-10 block">-->
                                <!-- Button -->
                                <!--<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                                    Add New Address
                                </button>
                            </div>-->
                        </div>
                    </div>
                    
                    <div class="flex-w flex-r bo10 p-t-15 p-b-20">
                        <span class="s-text18 w-size19 w-full-sm">
                            Payment Info:
                        </span>

                        <div class="w-size20 w-full-sm r">
                            <div class="rs2-select2 rs3-select2 rs4-select2 bo4 of-hidden m-t-8 m-b-12">
                                {{form.cc_number}}
                                {{form.cc_number.errors}}
                            </div>

                            <div class="rs2-select2 rs3-select2 rs4-select2 bo4 of-hidden m-t-8 m-b-12">
                                {{form.cc_expiry}}
                                {{form.cc_expiry.errors}}
                            </div>

                            <div class="rs2-select2 rs3-select2 rs4-select2 bo4 of-hidden m-t-8 m-b-12">
                                {{form.cc_code}}
                                {{form.cc_code.errors}}
                            </div>

                            <!--<div class="size14 trans-0-4 m-b-10 block">-->
                                <!-- Button -->
                                <!--<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                                    Add New Address
                                </button>
                            </div>-->
                        </div>
                    </div>

                    <!--  -->
                    <div class="flex-w flex-sb-m p-t-26 p-b-30">
                        <span class="m-text22 w-size19 w-full-sm">
                            Total:
                        </span>
                        <span class="m-text21 w-size20 w-full-sm r-text">
                            ${{ cart.get_total_price }}
                        </span>
                    </div>
                    <div>
                        
                    </div>
                    <div class="size15 trans-0-4">
                        <!-- Button -->
                        {% if cart %}
                            <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                                Proceed to Checkout
                            </button>
                        {% endif %}
                        </form>
                    </div>
                </form>
            </div>

            <!-- Total -->
            
        </div>
    </section>
{% endblock %}